db.words.insert([
	{chinese: '安', english: 'safe'},
	{chinese: '八', english: 'eight'},
	{chinese: '爸', english: 'father'},
	{chinese: '白', english: 'white'},
	{chinese: '百', english: 'hundred'},
	{chinese: '半', english: 'half'},
	{chinese: '幫', english: 'to help'},
	{chinese: '包', english: 'to cover'},
	{chinese: '北', english: 'north'},
	{chinese: '本', english: 'root'},
	{chinese: '比', english: 'to compare'},
	{chinese: '邊', english: 'side'},
	{chinese: '便', english: 'convenient'},
	{chinese: '別', english: 'other/something else'},
	{chinese: '病', english: 'illness'},
	{chinese: '不', english: 'no'},
	{chinese: '才', english: 'ability'},
	{chinese: '菜', english: 'vegetable'},
	{chinese: '茶', english: 'tea'},
	{chinese: '差', english: 'difference'},
	{chinese: '長', english: 'long/length'},
	{chinese: '常', english: 'always'},
	{chinese: '場', english: 'location'},
	{chinese: '唱', english: 'to sing'},
	{chinese: '車', english: 'car/vehicle'},
	{chinese: '吃', english: 'to eat'},
	{chinese: '出', english: 'to go out'},
	{chinese: '穿', english: 'to pierce'},
	{chinese: '次', english: 'next'},
	{chinese: '從', english: 'from'},
	{chinese: '錯', english: 'mistake'},
	{chinese: '答', english: 'to answer'},
	{chinese: '打', english: 'hit/dozen'},
	{chinese: '大', english: 'big'},
	{chinese: '但', english: 'but'},
	{chinese: '蛋', english: 'egg'},
	{chinese: '到', english: 'to arrive here'},
	{chinese: '道', english: 'direction/methods'},
	{chinese: '地', english: 'ground'},
	{chinese: '的', english: 'belonging to/possesive'},
	{chinese: '等', english: 'equal to'},
	{chinese: '第', english: 'prefix indicating ordinal number'},
	{chinese: '點', english: 'point'},
	{chinese: '電', english: 'electric'},
	{chinese: '店', english: 'store'},
	{chinese: '東', english: 'east'},
	{chinese: '動', english: 'to move'},
	{chinese: '都', english: 'many'},
	{chinese: '對', english: 'couple'},
	{chinese: '多', english: 'many'},
	{chinese: '餓', english: 'to be hungry'},
	{chinese: '兒', english: 'son'},
	{chinese: '二', english: 'two'},
	{chinese: '飯', english: 'steamed rice'},
	{chinese: '方', english: 'square'},
	{chinese: '房', english: 'house'},
	{chinese: '放', english: 'to release'},
	{chinese: '飛', english: 'to fly'},
	{chinese: '非', english: 'to not be'},
	{chinese: '分', english: 'to divide'},
	{chinese: '服', english: 'clothes/obey'},
	{chinese: '該', english: 'should'},
	{chinese: '剛', english: 'tough'},
	{chinese: '高', english: 'tall'},
	{chinese: '哥', english: 'elder brother'},
	{chinese: '歌', english: 'song'},
	{chinese: '個', english: 'item'},
	{chinese: '給', english: 'to give'},
	{chinese: '跟', english: 'to go with/follow'},
	{chinese: '更', english: 'to change/replace'},
	{chinese: '工', english: 'work'},
	{chinese: '關', english: 'to close'},
	{chinese: '貴', english: 'expensive'},
	{chinese: '國', english: 'country'},
	{chinese: '果', english: 'fruit'},
	{chinese: '過', english: 'to cross'},
	{chinese: '還', english: 'to return'},
	{chinese: '孩', english: 'child'},
	{chinese: '漢', english: 'male/han chinese'},
	{chinese: '好', english: 'good'},
	{chinese: '號', english: 'count(word)'},
	{chinese: '喝', english: 'to drink'},
	{chinese: '和', english: 'and'},
	{chinese: '黑', english: 'black'},
	{chinese: '很', english: 'very'},
	{chinese: '後', english: 'behind'},
	{chinese: '候', english: 'to wait'},
	{chinese: '花', english: 'flower'},
	{chinese: '話', english: 'speech'},
	{chinese: '壞', english: 'bad'},
	{chinese: '歡', english: 'happy'},
	{chinese: '回', english: 'to return'},
	{chinese: '會', english: 'to be able to'},
	{chinese: '活', english: 'to live'},
	{chinese: '火', english: 'fire'}
])

db.words.insert([{chinese:"安",english:"safe"},{chinese:"八",english:"eight"},{chinese:"爸",english:"father"},{chinese:"白",english:"white"},{chinese:"百",english:"hundred"},{chinese:"半",english:"half"},{chinese:"幫",english:"to help"},{chinese:"包",english:"to cover"},{chinese:"北",english:"north"},{chinese:"本",english:"root"},{chinese:"比",english:"to compare"},{chinese:"邊",english:"side"},{chinese:"便",english:"convenient"},{chinese:"別",english:"other/something else"},{chinese:"病",english:"illness"},{chinese:"不",english:"no"},{chinese:"才",english:"ability"},{chinese:"菜",english:"vegetable"},{chinese:"茶",english:"tea"},{chinese:"差",english:"difference"},{chinese:"長",english:"long/length"},{chinese:"常",english:"always"},{chinese:"場",english:"location"},{chinese:"唱",english:"to sing"},{chinese:"車",english:"car/vehicle"},{chinese:"吃",english:"to eat"},{chinese:"出",english:"to go out"},{chinese:"穿",english:"to pierce"},{chinese:"次",english:"next"},{chinese:"從",english:"from"},{chinese:"錯",english:"mistake"},{chinese:"答",english:"to answer"},{chinese:"打",english:"hit/dozen"},{chinese:"大",english:"big"},{chinese:"但",english:"but"},{chinese:"蛋",english:"egg"},{chinese:"到",english:"to arrive here"},{chinese:"道",english:"direction/methods"},{chinese:"地",english:"ground"},{chinese:"的",english:"belonging to/possesive"},{chinese:"等",english:"equal to"},{chinese:"第",english:"prefix indicating ordinal number"},{chinese:"點",english:"point"},{chinese:"電",english:"electric"},{chinese:"店",english:"store"},{chinese:"東",english:"east"},{chinese:"動",english:"to move"},{chinese:"都",english:"many"},{chinese:"對",english:"couple"},{chinese:"多",english:"many"},{chinese:"餓",english:"to be hungry"},{chinese:"兒",english:"son"},{chinese:"二",english:"two"},{chinese:"飯",english:"steamed rice"},{chinese:"方",english:"square"},{chinese:"房",english:"house"},{chinese:"放",english:"to release"},{chinese:"飛",english:"to fly"},{chinese:"非",english:"to not be"},{chinese:"分",english:"to divide"},{chinese:"服",english:"clothes/obey"},{chinese:"該",english:"should"},{chinese:"剛",english:"tough"},{chinese:"高",english:"tall"},{chinese:"哥",english:"elder brother"},{chinese:"歌",english:"song"},{chinese:"個",english:"item"},{chinese:"給",english:"to give"},{chinese:"跟",english:"to go with/follow"},{chinese:"更",english:"to change/replace"},{chinese:"工",english:"work"},{chinese:"關",english:"to close"},{chinese:"貴",english:"expensive"},{chinese:"國",english:"country"},{chinese:"果",english:"fruit"},{chinese:"過",english:"to cross"},{chinese:"還",english:"to return"},{chinese:"孩",english:"child"},{chinese:"漢",english:"male/han chinese"},{chinese:"好",english:"good"},{chinese:"號",english:"count(word)"},{chinese:"喝",english:"to drink"},{chinese:"和",english:"and"},{chinese:"黑",english:"black"},{chinese:"很",english:"very"},{chinese:"後",english:"behind"},{chinese:"候",english:"to wait"},{chinese:"花",english:"flower"},{chinese:"話",english:"speech"},{chinese:"壞",english:"bad"},{chinese:"歡",english:"happy"},{chinese:"回",english:"to return"},{chinese:"會",english:"to be able to"},{chinese:"活",english:"to live"},{chinese:"火",english:"fire"}])